[book]
authors = ["Robert Guthrie"]
language = "en"
multilingual = false
src = ""
title = "Enspiral Handbook"

[output.html]
no-section-label = true
edit-url-template = "https://github.com/enspiral/handbook/edit/main{path}"

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding
