[book]
authors = ["Various Enspiral Contributors"]
language = "en"
multilingual = false
src = "src"
title = "Enspiral Handbook"

[output.html]
no-section-label = true
edit-url-template = "https://github.com/robguthrie/handbook/edit/main/{path}"

[output.html.fold]
enable = false    # whether or not to enable section folding
level = 0         # the depth to start folding

[output.html.print]
enable = false    # include support for printable output
